import streamlit as st
from datetime import datetime

st.set_page_config(
    page_title="Blaize Bazaar - AI-Powered E-commerce Platform",
    page_icon="🔱",
    layout="wide"
)
logo_url = "static/Blaize.png"
st.sidebar.image(logo_url, use_column_width=True)

st.header("Welcome to Blaize Bazaar", divider="orange")
st.sidebar.info("**DISCLAIMER:** This workshop uses Amazon Bedrock foundation models and is not intended to collect any personally identifiable information (PII) from users. Please do not provide any PII when interacting with this workshop. The content generated by this workshop is for informational purposes only.")

st.write ("---")
    
# Add version info
st.sidebar.divider()
st.sidebar.caption(f"""
Version: 1.0.0
Last Updated: {datetime.now().strftime('%Y-%m-%d')}
""")

st.write("### What is Blaize Bazaar?")
st.markdown(
    """
    Blaize Bazaar is an advanced e-commerce platform that leverages the power of AWS Bedrock, Claude 3 Sonnet, and pgvector on Aurora PostgreSQL. Our platform offers comprehensive insights into product trends, inventory management, and personalized recommendations.
    
    Explore our suite of AI-powered tools designed to revolutionize your e-commerce experience:
    """
)
col1, col2, col3 = st.columns(3)

with col1:
    st.subheader("🔍 Product Insights")
    st.write("""
    Dive deep into your product data with our interactive dashboards. Analyze top-selling items, trending categories, and revenue metrics at a glance.
    
    - Top 10 Trending Categories
    - Highest Grossing Products
    - Best Selling Products by Category
    - General Spending Habits Analysis
    """)

with col2:
    st.subheader("🤖 AI-Powered Recommendations")
    st.write("""
    Harness the power of AI to generate personalized product recommendations and answer complex queries about your inventory.
    
    - Product Similarity Search
    - Personalized AI Recommendations
    - Natural Language Query Processing
    """)

with col3:
    st.subheader("📊 Knowledge Base & Bedrock Agents")
    st.write("""
    Leverage our advanced knowledge base and Bedrock Agents to get instant answers to your business questions and automate complex tasks.
    
    - Upload and Query Policy Documents
    - Interact with Bedrock Agents
    - Perform AI-assisted Tasks and Actions
    """)

st.write("---")
st.markdown("""### Sample Product Categories""")
col1, col2, col3, col4, col5 = st.columns(5)

with col1:
    st.image("static/automotive.png")
    st.write("Automotive Tools")

with col2:
    st.image("static/Sports.png")
    st.write("Sports")

with col3:
    st.image("static/Electronics.png")
    st.write("Electronics")

with col4:
    st.image("static/HomeDecor_1.png")
    st.write("Home Decor")

with col5:
    st.image("static/Accessories_1.png")
    st.write("Accessories")

st.write("---")
st.subheader("🚀 Getting Started")
st.markdown(
    """
    1. **Product Insights**: Start by exploring our Product Insights dashboard to get a comprehensive view of your e-commerce performance.
    2. **Product Recommendations**: Use our AI-powered recommendation engine to discover similar products and get personalized suggestions.
    3. **Upload Documents**: Enhance our knowledge base by uploading relevant documents to improve query responses.
    4. **Query Knowledge Base**: Ask questions about your product catalog, inventory, or business policies.
    5. **Bedrock Agents**: Interact with Bedrock agents for agentic workflows.
    """
)

st.write("---")
st.subheader("🛠️ Technologies Powering Blaize Bazaar")
tech_col1, tech_col2 = st.columns(2)

with tech_col1:
    st.write("**AWS Services:**")
    st.markdown("""
    - Amazon Bedrock (Claude 3 and Titan Text)
    - Aurora PostgreSQL with pgvector
    - AWS Lambda
    - Amazon S3
    """)

with tech_col2:
    st.write("**Key Features:**")
    st.markdown("""
    - Vector Similarity Search
    - Retrieval Augmented Generation (RAG)
    - Natural Language Processing
    - Real-time Market Insights
    - Interactive Visualizations
    """)

st.write("---")
st.subheader('✍️ Retrieval Augmented Generation (RAG) Architecture')
st.image("static/RAG_Arch.png", use_column_width="auto", caption="RAG Architecture")
st.write("---")